version: "3"

services:
  app:
    image: docker-nextjs-techtime-dev
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./components:/app/components
      - ./lib:/app/lib
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
