export const courses = [
  {
    image: "/images/popularCourses/image1.png",
    category: "design",
    header: "introduction to user research in ux design",
    time: "23hrs 50mins",
    star: "4.7k",
    downloads: "(32.7k+)",
    userImg: "/images/popularCourses/user1.png",
    userName: "leonard victor",
    lessons: "15 lessons",
    amount: "$15.00",
  },
  {
    image: "/images/popularCourses/image2.png",
    category: "marketing",
    header: "introduction to  new marketing audience ",
    time: "22hrs 30mins",
    star: "4.7k",
    downloads: "(8.7k+)",
    userImg: "/images/popularCourses/user2.png",
    userName: "Jeffrey williams",
    lessons: "15 lessons",
    amount: "$32.00",
  },
  {
    image: "/images/popularCourses/image3.png",
    category: "development",
    header: "introduction to html, css & bootstrap",
    time: "45hrs 50mins",
    star: "4.7k",
    downloads: "(12.7k+)",
    userImg: "/images/popularCourses/user3.png",
    userName: "claretta mason",
    lessons: "55 lessons",
    amount: "$55.00",
  },
  {
    image: "/images/popularCourses/image4.png",
    category: "development",
    header: "introduction to javascript, git & GitHub",
    time: "30hrs 50mins",
    star: "4.7k",
    downloads: "(32.7k+)",
    userImg: "/images/popularCourses/user4.png",
    userName: "Jessica duke",
    lessons: "22 lessons",
    amount: "$45.00",
  },
  {
    image: "/images/popularCourses/image5.png",
    category: "marketing",
    header: "introduction to outroom  marketing analysis",
    time: "33hrs 50mins",
    star: "4.7k",
    downloads: "(4.7k+)",
    userImg: "/images/popularCourses/user5.png",
    userName: "Samuel jacobs",
    lessons: "26 lessons",
    amount: "$25.00",
  },
  {
    image: "/images/popularCourses/image6.png",
    category: "marketing",
    header: "introduction to live  marketing analysis",
    time: "10hrs 50mins",
    star: "4.7k",
    downloads: "(15.7k+)",
    userImg: "/images/popularCourses/user6.png",
    userName: "adam smith",
    lessons: "32 lessons",
    amount: "$25.00",
  },
];
